'use strict';

require('./PLURAL_NAME_LOWERCASE_CAMELIZED/edit');
require('./PLURAL_NAME_LOWERCASE_CAMELIZED/index');
require('./PLURAL_NAME_LOWERCASE_CAMELIZED/new');
require('./PLURAL_NAME_LOWERCASE_CAMELIZED/show');
